### ISSUE TITLE
Youtube metadata api stuffs

### ISSUE THREAD

**Issue by admalledd** [cnlohr/cnlohr_social_media_tools#4]
Just using this as a brain dump from the stream as well.

* Different way to get streamID, based on channel ID

https://developers.google.com/apis-explorer/#p/youtube/v3/youtube.search.list?part=snippet&channelId=UCG7yIWtVwcENg_ZS-nahg5g&eventType=live&type=video&_h=1&

    GET https://www.googleapis.com/youtube/v3/search?part=snippet&channelId=UCG7yIWtVwcENg_ZS-nahg5g&eventType=live&type=video

    {
     "kind": "youtube#searchListResponse",
     "etag": "\"95M1zlW0txkV42I4OG1Zscxrg5A/NvC1oD1K0WF5_14mC8YTSe7edNY\"",
     "regionCode": "US",
     "pageInfo": {
      "totalResults": 1,
      "resultsPerPage": 5
     },
     "items": [
      {
       "kind": "youtube#searchResult",
       "etag": "\"95M1zlW0txkV42I4OG1Zscxrg5A/2TYFvh37MeOoNzGUShceRT3G0uo\"",
       "id": {
        "kind": "youtube#video",
        "videoId": "16NSQORHRqU"
       },
       "snippet": {
        "publishedAt": "2018-04-01T20:51:43.000Z",
        "channelId": "UCG7yIWtVwcENg_ZS-nahg5g",
        "title": "Making tools to make programming livestreams more fun",
        "description": "We're going to be working on my \"cnlohr_social_media_tools\" toolset in this livestream today... Including the legal use of music! Come out to see some live ...",
        "thumbnails": {
         "default": {
          "url": "https://i.ytimg.com/vi/16NSQORHRqU/default_live.jpg",
          "width": 120,
          "height": 90
         },
         "medium": {
          "url": "https://i.ytimg.com/vi/16NSQORHRqU/mqdefault_live.jpg",
          "width": 320,
          "height": 180
         },
         "high": {
          "url": "https://i.ytimg.com/vi/16NSQORHRqU/hqdefault_live.jpg",
          "width": 480,
          "height": 360
         }
        },
        "channelTitle": "CNLohr",
        "liveBroadcastContent": "live"
       }
      }
     ]
    }

**Comment by cnlohr** [comment]
This was superseded by new work flow.
